import { IncidentAlert, ShelterItem, DispatchService } from './types';

export const INITIAL_ALERTS: IncidentAlert[] = [
  {
    id: 'alert-1',
    category: 'emergency',
    titleEn: 'TIDAL SURGE & FLOOD ALERT • Halishahar & Agrabad Lowlands',
    titleBn: 'জোয়ারের পানির সতর্কতা • হালিশহর ও আগ্রাবাদ নিম্নাঞ্চল',
    subtitleEn: 'জোয়ার ও বৃষ্টির সতর্কতা • নিচু উপকূলীয় এলাকা এড়িয়ে চলুন',
    subtitleBn: 'জোয়ার ও বৃষ্টির সতর্কতা • নিচু উপকূলীয় এলাকা এড়িয়ে চলুন',
    descriptionEn: 'Tidal surge from Karnaphuli estuary & Bay of Bengal is rising (+0.9m). Avoid submerged coastal access roads and Chaktai canal corridors.',
    descriptionBn: 'কর্ণফুলী মোহনা ও বঙ্গোপসাগরের জোয়ারের পানি দ্রুত বৃদ্ধি পাচ্ছে (+০.৯ মি)। নিম্নাঞ্চলের উপকূলীয় সড়ক ও চাক্তাই খাল সংলগ্ন এলাকা পরিহার করুন।',
    timeEn: '5 min ago',
    timeBn: '৫ মিনিট আগে',
    location: 'Agrabad & Halishahar Lowlands',
    verified: true,
    isSimulation: true,
    steps: [
      {
        id: 'step-1',
        textEn: 'Move to higher ground or designated cyclone/flood shelters',
        textBn: 'উঁচু স্থানে বা নির্ধারিত সাইক্লোন ও বন্যা আশ্রয়কেন্দ্রে যান',
        icon: 'arrow_upward',
        checked: true,
      },
      {
        id: 'step-2',
        textEn: 'Stay away from open tidal canals & low-lying embankments',
        textBn: 'উন্মুক্ত জোয়ারের খাল ও নিচু বাঁধ থেকে নিরাপদ দূরত্বে থাকুন',
        icon: 'warning',
        checked: true,
      },
      {
        id: 'step-3',
        textEn: 'Keep phone charged & backup power bank accessible',
        textBn: 'ফোন চার্জ রাখুন এবং ব্যাকআপ পাওয়ার ব্যাংক হাতের কাছে রাখুন',
        icon: 'battery_charging_full',
        checked: false,
      },
      {
        id: 'step-4',
        textEn: 'Listen to designated Chattogram Port & Red Crescent volunteer updates',
        textBn: 'চট্টগ্রাম বন্দর ও রেড ক্রিসেন্ট স্বেচ্ছাসেবকদের নির্দেশনা মেনে চলুন',
        icon: 'record_voice_over',
        checked: false,
      },
    ],
  },
  {
    id: 'alert-2',
    category: 'watch',
    titleEn: 'MONSOON SQUALL WARNING • Bay of Bengal & Patenga',
    titleBn: 'প্রবল বর্ষণ ও দমকা হাওয়ার সতর্কতা • বঙ্গোপসাগর ও পতেঙ্গা',
    subtitleEn: 'উপকূলীয় সতর্কতা • মাছ ধরার ট্রলারকে নিরাপদ আশ্রয়ে থাকার নির্দেশ',
    subtitleBn: 'উপকূলীয় সতর্কতা • মাছ ধরার ট্রলারকে নিরাপদ আশ্রয়ে থাকার নির্দেশ',
    descriptionEn: 'Squally weather over Chattogram coast. Expected 50mm cloudburst with gusts up to 45 km/h over the next 2 hours.',
    descriptionBn: 'চট্টগ্রাম উপকূলে দমকা হাওয়া ও ভারি বৃষ্টি। আগামী ২ ঘণ্টায় ৪৫ কিমি/ঘণ্টা বেগে বাতাসসহ প্রায় ৫০ মিমি বৃষ্টিপাতের আশঙ্কা।',
    timeEn: '20 min ago',
    timeBn: '২০ মিনিট আগে',
    location: 'Patenga & Coastal Belt',
    verified: true,
  },
  {
    id: 'alert-3',
    category: 'safe',
    titleEn: 'ALL CLEAR • Khulshi & Nasirabad Elevated Ridges',
    titleBn: 'বিপদমুক্ত • খুলশী ও নাসিরাবাদ পাহাড়ি উঁচু এলাকা',
    subtitleEn: 'বিপদমুক্ত • স্বাভাবিক যান চলাচল ও শুষ্ক সড়ক',
    subtitleBn: 'বিপদমুক্ত • স্বাভাবিক যান চলাচল ও শুষ্ক সড়ক',
    descriptionEn: 'High-elevation zones in Khulshi and Nasirabad remain completely safe from tidal surge. Normal transit active.',
    descriptionBn: 'খুলশী ও নাসিরাবাদের উঁচু এলাকায় জোয়ারের কোনো প্রভাব নেই। সাধারণ যান চলাচল সম্পূর্ণ স্বাভাবিক।',
    timeEn: '2 hrs ago',
    timeBn: '২ ঘণ্টা আগে',
    location: 'Khulshi, Chattogram',
    verified: true,
  },
  {
    id: 'alert-4',
    category: 'watch',
    titleEn: 'KARNAPHULI SLUICE GATE MONITORING',
    titleBn: 'কর্ণফুলী স্লুইস গেট নিরীক্ষণ নোটিশ',
    subtitleEn: 'জোয়ারের পানি নিয়ন্ত্রণে রেগুলেটর পাম্প চালু',
    subtitleBn: 'জোয়ারের পানি নিয়ন্ত্রণে রেগুলেটর পাম্প চালু',
    descriptionEn: 'Chattogram Development Authority (CDA) tidal regulator gates closed during high tide to protect city interior.',
    descriptionBn: 'উচ্চ জোয়ারের সময়ে শহরের ভেতরে পানি প্রবেশ ঠেকাতে সিডিএ রেগুলেটর গেটসমূহ বন্ধ রাখা হয়েছে।',
    timeEn: '3 hrs ago',
    timeBn: '৩ ঘণ্টা আগে',
    location: 'Karnaphuli Estuary',
    verified: true,
  }
];

export const SHELTERS: ShelterItem[] = [
  {
    id: 'shelter-1',
    name: 'Agrabad Multi-Purpose Cyclone Shelter',
    nameBn: 'আগ্রাবাদ বহুমুখী সাইক্লোন ও কমিউনিটি শেল্টার',
    type: 'shelter',
    spotsAvailable: 680,
    totalSpots: 900,
    distanceKm: 1.1,
    walkTimeMinutes: 13,
    verifiedTime: '3m ago',
    status: 'open',
    address: 'Road 4, Agrabad Commercial Area, Chattogram',
    phone: '+880-1711-445522',
    coordinates: { x: 115, y: 85 },
  },
  {
    id: 'shelter-2',
    name: 'Chittagong Medical College Hospital (CMCH)',
    nameBn: 'চট্টগ্রাম মেডিকেল কলেজ হাসপাতাল (সিএমসিএইচ)',
    type: 'hospital',
    spotsAvailable: 58,
    totalSpots: 160,
    distanceKm: 2.6,
    walkTimeMinutes: 30,
    verifiedTime: '6m ago',
    status: 'open',
    address: 'KB Fazlul Kader Road, Panchlaish, Chattogram',
    phone: '+880-1819-334455',
    coordinates: { x: 295, y: 130 },
  },
  {
    id: 'shelter-3',
    name: 'Naval Rescue & Disaster Unit 02',
    nameBn: 'নৌবাহিনী ও কোস্টগার্ড উদ্ধারকারী দল ০২',
    type: 'rescue',
    spotsAvailable: 16,
    totalSpots: 25,
    distanceKm: 1.9,
    walkTimeMinutes: 22,
    verifiedTime: '2m ago',
    status: 'open',
    address: 'Karnaphuli River Embankment, Chattogram',
    phone: '+880-1912-778899',
    coordinates: { x: 310, y: 280 },
  },
  {
    id: 'shelter-4',
    name: 'GEC Convention Relief Hub',
    nameBn: 'জিইসি কনভেনশন সেন্টার আশ্রয়কেন্দ্র',
    type: 'shelter',
    spotsAvailable: 420,
    totalSpots: 600,
    distanceKm: 2.3,
    walkTimeMinutes: 27,
    verifiedTime: '10m ago',
    status: 'open',
    address: 'GEC Circle, Nasirabad, Chattogram',
    phone: '+880-1715-667788',
    coordinates: { x: 160, y: 190 },
  }
];

export const DISPATCH_SERVICES: DispatchService[] = [
  {
    id: 'medical',
    titleEn: 'Medical Help',
    titleBn: 'চিকিৎসা সাহায্য',
    descEn: 'Ambulance, first-aid kit, paramedics & triage',
    descBn: 'অ্যাম্বুলেন্স, প্রাথমিক চিকিৎসা কিট ও প্যারামেডিক',
    icon: 'medical_services',
    colorClass: 'bg-error-container text-on-error-container',
  },
  {
    id: 'rescue',
    titleEn: 'Rescue / Evacuation',
    titleBn: 'উদ্ধার সহায়তা',
    descEn: 'Stranded in water, rising flood, structural risk',
    descBn: 'পানিবন্দী অবস্থা, দ্রুত পানি বৃদ্ধি বা ভবনের ঝুঁকি',
    icon: 'kayaking',
    colorClass: 'bg-secondary-container text-on-secondary-container',
  },
  {
    id: 'shelter',
    titleEn: 'Shelter Assistance',
    titleBn: 'নিরাপদ আশ্রয়',
    descEn: 'Need dry lodging, storm shelter & transport pick-up',
    descBn: 'শুকনো আশ্রয়, ঝড় আশ্রয়কেন্দ্র ও যাতায়াত পিকআপ',
    icon: 'roofing',
    colorClass: 'bg-primary-fixed text-on-primary-fixed',
  },
  {
    id: 'food_water',
    titleEn: 'Clean Food & Water',
    titleBn: 'খাবার ও পানীয়',
    descEn: 'Emergency water purification & dry food rations',
    descBn: 'জরুরি বিশুদ্ধ পানি ও শুকনো খাবারের রেশন',
    icon: 'water_drop',
    colorClass: 'bg-tertiary-fixed text-on-tertiary-fixed',
  },
  {
    id: 'missing_person',
    titleEn: 'Missing Person Alert',
    titleBn: 'নিখোঁজ ব্যক্তি সন্ধান',
    descEn: 'Report or trace family members, children, or elders',
    descBn: 'পরিবারের নিখোঁজ সদস্য, শিশু বা বয়োবৃদ্ধের সন্ধান',
    icon: 'person_search',
    colorClass: 'bg-surface-variant text-on-surface',
  },
  {
    id: 'hotlines',
    titleEn: 'Hotlines & Dispatch',
    titleBn: 'জরুরি হটলাইন',
    descEn: 'National 999 Direct, Red Crescent & SafeNow AI Voice',
    descBn: 'জাতীয় জরুরি ৯৯৯, রেড ক্রিসেন্ট ও সেফনাউ ভয়েস',
    icon: 'ring_volume',
    colorClass: 'bg-primary-container text-on-primary-container',
  }
];

export const NEIGHBORHOODS = [
  { name: 'Agrabad, Chattogram', safe: true, elevation: '+12m' },
  { name: 'GEC Circle, Chattogram', safe: true, elevation: '+18m', statusText: 'Elevated High Ground' },
  { name: 'Halishahar, Chattogram', safe: false, statusText: 'Tidal Inundation Alert', elevation: '+4m' },
  { name: 'Patenga Coastal, Chattogram', safe: false, statusText: 'Bay Surge Advisory', elevation: '+3m' },
  { name: 'Khulshi Hills, Chattogram', safe: true, elevation: '+28m', statusText: 'Surge Free Ridge' },
  { name: 'Nasirabad, Chattogram', safe: true, elevation: '+16m' },
  { name: 'Bakalia Lowlands, Chattogram', safe: false, statusText: 'Chaktai Canal Overflow', elevation: '+5m' },
];

